import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {describe,it,expect} from 'vitest';
import {verifyExecutable,publishEnvironment,provision,extractVerified} from './provision-runtime-freeze-gh.mjs';
const hash=b=>'sha256:'+createHash('sha256').update(b).digest('hex');
function fixture(fn){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'gh-provision-test-')));try{fn(dir);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
describe('pinned gh provisioning (fake bytes/processes; no network or gh execution)',()=>{
 it('bounds extractor failure and tolerates target mode changes inside private parent',()=>fixture(dir=>{fs.chmodSync(dir,0o700);const target=path.join(dir,'extract');fs.mkdirSync(target);const expected={executableSizeBytes:4,executableSha256:hash('fake')};expect(()=>extractVerified('archive',target,dir,expected,()=>{throw Error('extract failure');},{})).toThrow();const run=(exe,args,opts)=>{expect(exe).toBe('/usr/bin/dpkg-deb');expect(opts.timeout).toBe(30000);expect(opts.killSignal).toBe('SIGKILL');fs.chmodSync(target,0o755);fs.mkdirSync(path.join(target,'usr/bin'),{recursive:true});fs.writeFileSync(path.join(target,'usr/bin/gh'),'fake',{mode:0o755});};expect(extractVerified('archive',target,dir,expected,run,{}).bytes).toBe(4);expect(fs.statSync(dir).mode&0o777).toBe(0o700);}));
 it('rejects oversize download before extraction or publication',()=>fixture(dir=>{const env=path.join(dir,'env');fs.writeFileSync(env,'');let calls=0;expect(()=>provision({platform:'linux',arch:'x64',temp:dir,environmentFile:env,run:(exe,args)=>{calls++;expect(args[0]).toBe('-q');fs.truncateSync(args[args.indexOf('--output')+1],67108865);}})).toThrow();expect(calls).toBe(1);expect(fs.readFileSync(env,'utf8')).toBe('');}));
 it('validates actual filesystem bytes and publishes once',()=>fixture(dir=>{const p=path.join(dir,'gh'),env=path.join(dir,'env');fs.writeFileSync(p,'fake',{mode:0o755});fs.writeFileSync(env,'');const r=verifyExecutable(p,{executableSizeBytes:4,executableSha256:hash('fake')});publishEnvironment(env,r.path);expect(fs.readFileSync(env,'utf8')).toBe(`TAILING_RUNTIME_FREEZE_GH_PATH=${p}\n`);expect(()=>publishEnvironment(env,p)).toThrow();}));
 for(const kind of ['size','hash','mode','symlink','hardlink'])it('rejects '+kind,()=>fixture(dir=>{let p=path.join(dir,'gh');fs.writeFileSync(p,'fake',{mode:0o755});const expected={executableSizeBytes:4,executableSha256:hash('fake')};if(kind==='size')expected.executableSizeBytes=5;if(kind==='hash')expected.executableSha256=hash('evil');if(kind==='mode')fs.chmodSync(p,0o644);if(kind==='symlink'){fs.symlinkSync(p,path.join(dir,'link'));p=path.join(dir,'link');}if(kind==='hardlink')fs.linkSync(p,path.join(dir,'link'));expect(()=>verifyExecutable(p,expected)).toThrow();}));
 for(const kind of ['platform','arch','temp','environment','download','truncated'])it('rejects '+kind+' without publication',()=>fixture(dir=>{const env=path.join(dir,'env');fs.writeFileSync(env,'');let called=0;const opts={platform:'linux',arch:'x64',temp:dir,environmentFile:env,run:(exe,args)=>{called++;expect(exe).toBe('/usr/bin/curl');expect(args).toContain('--max-filesize');expect(args).toContain('--max-redirs');if(kind==='download')throw Error('timeout');fs.writeFileSync(args[args.indexOf('--output')+1],'truncated');}};if(kind==='platform')opts.platform='darwin';if(kind==='arch')opts.arch='arm64';if(kind==='temp')opts.temp='../unsafe';if(kind==='environment')opts.environmentFile=env+'\n';expect(()=>provision(opts)).toThrow();expect(fs.readFileSync(env,'utf8')).toBe('');expect(called).toBe(['download','truncated'].includes(kind)?1:0);}));
 it('rejects malformed or linked environment file',()=>fixture(dir=>{const env=path.join(dir,'env');fs.writeFileSync(env,'incomplete');expect(()=>publishEnvironment(env,'/safe/gh')).toThrow();fs.writeFileSync(env,'');fs.linkSync(env,path.join(dir,'link'));expect(()=>publishEnvironment(env,'/safe/gh')).toThrow();}));
});
