import { test } from 'vitest';
import assert from 'node:assert/strict';
import {initialize,advance,fork,exportCheckpoint,restoreCheckpoint,AR_INTERPRETATION,CONFIG,UNITS,type State} from './ar-vv-adapter';
import {createDefaultStructureDraft,makeFiniteNetCharge,finalizeStructureDocument} from './structure-document';
import {sha256DigestValue} from './canonical-json';
// Development-only N3 triangle, distinct from all preregistered native inputs.
function initial(reverse=false){const d=createDefaultStructureDraft();d.finiteSystem!.netCharge=makeFiniteNetCharge(0);d.atoms=[[0,0,0],[4.1,0,0],[0,4.2,.1]].map((p,i)=>({id:`dev-${i}`,element:{atomicNumber:18,symbol:'Ar'},position:{x:p[0],y:p[1],z:p[2]},formalCharge:null,isotope:null}));if(reverse)d.atoms.reverse();return {document:finalizeStructureDocument(d),velocities:[{atomId:'dev-2',velocity:[0,0,.00003]},{atomId:'dev-0',velocity:[.00004,0,0]},{atomId:'dev-1',velocity:[-.00004,0,0]}],dtTicks:2,confirmation:AR_INTERPRETATION};}
function state(){return initialize(initial());}
function step(s:State,n:number){const r=advance(s,n);if(r.decision!=='advanced')throw new Error(r.reason);assert.equal(r.decision,'advanced');return r;}
// This test is registered first: no initialize call precedes these checks.
test('fixed unit records are immutable before the first initialization',()=>{for(const quantity of Object.values(UNITS)){assert.equal(Object.isFrozen(quantity),true);assert.equal(Reflect.defineProperty(quantity,'unit',{value:'altered'}),false);}const s=state();assert.deepEqual(s.physical.units,UNITS);assert.equal(s.physical.units.energy.unit,'kJ/mol');assert.equal(s.physical.units.force.unit,'kJ mol^-1 angstrom^-1');});
test('explicit root validation and sorted ID mapping consume existing backend',()=>{const a=state(),b=initialize(initial(true));assert.equal(a.physicalDigest,b.physicalDigest);assert.deepEqual(a.physical.sites.map(x=>x.atomId),['dev-0','dev-1','dev-2']);assert.equal(a.physical.sites[2].velocity[2],.00003);assert.equal(a.physical.model.mass,39.95);assert.equal(a.physical.tick,0);assert.equal(a.physical.endTick,800);assert.equal(a.authenticatedProvenance,false);assert.ok(Object.isFrozen(a));assert.throws(()=>initialize({...initial(),confirmation:null}));assert.throws(()=>initialize({...initial(),dtTicks:3}));});
test('complete400 equals200 checkpoint replay then200 physical state/time, not logs',()=>{const s=state(),a=step(s,400),half=step(s,200),restored=restoreCheckpoint(exportCheckpoint(half.state)),b=step(restored,200);assert.equal(a.frames.length,400);assert.equal(a.state.physical.tick,800);assert.equal(a.state.physicalDigest,b.state.physicalDigest);assert.deepEqual(a.state.physical,b.state.physical);assert.notEqual(a.state.stateDigest,b.state.stateDigest);assert.equal(advance(a.state,1).decision,'abstain');});
test('identity fork exact physical; coordinate fork keeps time/v/rootP0, records deltaH not work',()=>{const s=step(state(),4).state,identity=fork(s,[]);assert.equal(identity.physicalDigest,s.physicalDigest);const p=s.physical.sites[0].position,c=fork(s,[{atomId:'dev-0',position:[p[0]+.005,p[1],p[2]]}]);assert.equal(c.physical.tick,s.physical.tick);assert.deepEqual(c.physical.sites.map(a=>a.velocity),s.physical.sites.map(a=>a.velocity));assert.deepEqual(c.branch.p0,s.branch.p0);assert.equal(c.branch.parentStateDigest,s.stateDigest);assert.equal(c.branch.deltaH,c.physical.h-s.physical.h);assert.equal(c.branch.h0,c.physical.h);assert.equal(c.branch.deltaHIsWork,false);assert.notEqual(c.physicalDigest,s.physicalDigest);assert.equal(restoreCheckpoint(exportCheckpoint(c)).stateDigest,c.stateDigest);assert.throws(()=>fork(s,[{atomId:'missing',position:[1,2,3]}]));});
test('atomic budget and discrete-domain failures never return partial state/frames',()=>{const s=state(),before=exportCheckpoint(s);for(const n of [0,401,1.5,Infinity])assert.deepEqual({...advance(s,n),reason:null},{decision:'abstain',reason:null,state:null,frames:null});assert.deepEqual(exportCheckpoint(s),before);assert.throws(()=>fork(s,[{atomId:'dev-1',position:[.1,0,0]}]));assert.deepEqual(exportCheckpoint(s),before);const input=initial();input.velocities[0].velocity=[.011,0,0];assert.throws(()=>initialize(input));assert.equal(advance(JSON.parse(new TextDecoder().decode(before)).state,1).decision,'abstain');});
test('second-step domain violation atomically discards an internally completed first step',()=>{
 const d=createDefaultStructureDraft();d.finiteSystem!.netCharge=makeFiniteNetCharge(0);d.atoms=[0,2.727].map((x,i)=>({id:`close-${i}`,element:{atomicNumber:18,symbol:'Ar'},position:{x,y:0,z:0},formalCharge:null,isotope:null}));
 const s=initialize({document:finalizeStructureDocument(d),velocities:[{atomId:'close-0',velocity:[.005,0,0]},{atomId:'close-1',velocity:[-.005,0,0]}],dtTicks:2,confirmation:AR_INTERPRETATION}),before=exportCheckpoint(s);
 assert.equal(advance(s,1).decision,'advanced');const failed=advance(s,2);assert.equal(failed.decision,'abstain');assert.equal(failed.state,null);assert.equal(failed.frames,null);assert.deepEqual(exportCheckpoint(s),before);
});
test('nonzero-tick identity forks preserve H0 and cumulative diagnostics through checkpoint',()=>{
 const s=step(state(),12).state;assert.ok(s.branch.maxEnergyDrift>0);
 for(const edits of [[],[{atomId:s.physical.sites[0].atomId,position:s.physical.sites[0].position}]]){
   const f=fork(s,edits);assert.equal(f.physicalDigest,s.physicalDigest);assert.equal(f.branch.h0,s.branch.h0);assert.equal(f.branch.maxEnergyDrift,s.branch.maxEnergyDrift);assert.deepEqual(f.branch.maxMomentumResidual,s.branch.maxMomentumResidual);assert.equal(restoreCheckpoint(exportCheckpoint(f)).stateDigest,f.stateDigest);
 }
});
test('bounded journal and restore cannot reset clock or accept caller-rehashed fake state',()=>{let s=state();for(let i=0;i<32;i++)s=fork(s,[]);assert.equal(s.journal.length,CONFIG.maxActions);assert.throws(()=>fork(s,[]));assert.equal(advance(s,1).decision,'abstain');const checkpoint=JSON.parse(new TextDecoder().decode(exportCheckpoint(step(state(),2).state)));checkpoint.state.physical.tick=0;checkpoint.state.physical.timeFs=0;checkpoint.state.physicalDigest=sha256DigestValue(checkpoint.state.physical);const {stateDigest:_ignored,...base}=checkpoint.state;assert.ok(_ignored);checkpoint.state.stateDigest=sha256DigestValue(base);assert.throws(()=>restoreCheckpoint(new TextEncoder().encode(JSON.stringify(checkpoint))),/does not replay/);});
test('strict checkpoint duplicates, versions, extra fields, bytes and getter data rejected',()=>{const b=exportCheckpoint(state()),text=new TextDecoder().decode(b);assert.throws(()=>restoreCheckpoint(new TextEncoder().encode(text.replace('{','{"schemaVersion":"duplicate",'))));assert.throws(()=>restoreCheckpoint(new Uint8Array(1048577)));const v=JSON.parse(text);v.extra=true;assert.throws(()=>restoreCheckpoint(new TextEncoder().encode(JSON.stringify(v))));v.extra=undefined;v.schemaVersion='other';delete v.extra;assert.throws(()=>restoreCheckpoint(new TextEncoder().encode(JSON.stringify(v))));const x=initial();Object.defineProperty(x,'confirmation',{get(){throw new Error('getter must not execute');},enumerable:true});assert.throws(()=>initialize(x),/enumerable defined data/);assert.throws(()=>initialize({...initial(),extra:'x'.repeat(131073)}),/byte limit/);});
test('fresh build-repeat, full-step KE, finite nonzero motion and 1tick horizon',()=>{const a=step(state(),5),b=step(state(),5);assert.deepEqual(a.frames,b.frames);assert.equal(a.state.physicalDigest,b.state.physicalDigest);assert.notDeepEqual(a.frames[0].sites[0].position,state().physical.sites[0].position);for(const f of a.frames){assert.equal(f.timeFs,f.tick*.125);assert.equal(f.h,f.pe+f.ke);assert.ok(f.ke>0);}const small=initialize({...initial(),dtTicks:1});assert.equal(step(small,2).state.physical.tick,2);});
